### ISSUE TITLE
Platform common

### ISSUE THREAD

**Issue by segalion** [fermartv/emt_madrid#1]
Could be great include platform parameters on common part, and sensor for each bus-stop pair....

sensor:
  - platform: emt_madrid
    email: !secret EMT_EMAIL
    password: !secret EMT_PASSWORD
    stop: "72"
    line: "27"
    name: "Bus 27 en Cibeles"
    icon: "mdi:fountain"

  - platform: emt_madrid
    email: !secret EMT_EMAIL
    password: !secret EMT_PASSWORD
    stop: "23"
    line: "12"
    name: "Bus 27 en Other"
    icon: "mdi:fountain"
...

Seems that component is using http "requests", so I think that HA will make a thread for each sensor, what could be a little heavy for a lot of sensors...

Maybe a better aproach could be an only-one platform and and all sensors updated at a time.
Could be great too a sensor for a stop, with all next bus and times inside atribute sensors... for each stop.

**Comment by fermartv** [comment]
Thanks for your suggestion!
I don't quite understand your request. You mean to have something like this?:

```
sensor:
  - platform: emt_madrid
    email: !secret EMT_EMAIL
    password: !secret EMT_PASSWORD
    stops:
	  - stop: "72"
	    line: "27"
	    name: "Bus 27 en Cibeles"
	    icon: "mdi:fountain"

	  - stop: "35"
	    line: "67"
	    name: "Bus 67 en other"
	    icon: "mdi:fountain"
```

How many sensors do you need? For my personal use case, I just needed 2 and that's why I thought that having them independently would be easier to manage.
