### ISSUE TITLE
Updating to 2.0

### ISSUE THREAD

**Issue by PozoSer** [fermartv/emt_madrid#4]
First of all, thanks for the update! I've using this for a year and it's been wonderful.

If I understood correctly, the new config for several stops should be as follows:

```
sensor:
  - platform: emt_madrid
    email: !MY EMAIL
    password: !MY PASSWORD
    stop: 1
    lines:
        - "1"
    name: "!My stop #1"
    icon: "mdi:bus"
  - platform: emt_madrid
    email: !MY EMAIL
    password: !MY PASSWORD
    stop: 5
    lines:
        - "149"
    name: "!My stop #2"
    icon: "mdi:bus

```
Am I correct? If so, how should I add the sensors back to the dashboard? I am not able to find them on the search list by their previous names.

**Comment by fermartv** [comment]
Hi! That's almost correct. The name field is no longer supported and it's generated automatically. This is the correct configuration:
```
sensor:
  - platform: emt_madrid
    email: !MY EMAIL
    password: !MY PASSWORD
    stop: 1
    lines:
        - "1"
    icon: "mdi:bus"
  - platform: emt_madrid
    email: !MY EMAIL
    password: !MY PASSWORD
    stop: 5
    lines:
        - "149"
    icon: "mdi:bus"
```


For your case you can find the sensor names that start with:

- Bus 1
- Bus 149 

Let me know if it works for you! :)
